### ISSUE TITLE
Run tests and save logs

### ISSUE THREAD

**Issue by UberlyMaxxor** [erikjoh/strongbox#5]

**Comment by erikjoh** [comment]
I interpret this requirement as being fulfilled by our Jenkins that runs tests on each PR / branch and saves them. So I'm closing this for now.

**Comment by alanihre** [comment]
We need test logs for before the refactoring, is this available on Jenkins? @Eika96

**Comment by alanihre** [comment]
Test logs before refactor: https://litinc.se/job/Assignment4-PR/2/
